### PR TITLE
Add failing test demonstrating double registering of events

### PR DESCRIPTION
**Pull request by kbond**
This PR is a failing test demonstrating the issue described in #37.

This issue causes problems when using a library like spatie/laravel-activitylog. In this library specifically, it is possible for children to trigger double activities.

I am not sure how best to solve - ideas welcome!

### CODE REVIEW

**Comment by dallincoons** [comment]
Honestly, I kind of think we should remove the automatic child observer registration. This is behind the scenes magic that isn't necessary and I think is going to cause more problems as we're already seeing. I think it should be left to the user to implement if they want to deviate from the normal observer behavior, or at the very least this should be broken out to another trait to make it opt-in. @calebporzio

**Comment by wfeller** [comment]
Hey @kbond, just noticed the issue yesterday, sorry for the delay :|

Can you take a look at [this commit](https://github.com/wfeller/parental/commit/e783f3ac435df85072f37aa428ed2fbe53d3a89d) and let me know if that solves your problem?

The tests work as intended when being run alone at the moment, but somehow fail when running all of them at once. I'm still trying to figure out why that is...

@dallincoons Good idea, I can extract that behaviour into its own trait if it isn't what people expect.

**Comment by kbond** [comment]
No worries @wfeller - thanks for looking into this!

I looked at your commit but your fork is significantly different. I tried pulling some of the code from your solution but wasn't able to get this PR's tests passing.

**Comment by wfeller** [comment]
Hey @kbond, can you take a look at [this version](https://github.com/wfeller/parental-test/blob/master/src/HasChildren.php)? It's based on the master fork and seems to work for me.

**Comment by calebporzio** [comment]
I'm not going to put my brain on this right now because you all are - hopefully, you all come to a good solution. When you do, I'll pull it in. I'm open the extra trait if Y'all feel it's best.

**Comment by kbond** [comment]
Thanks @wfeller! Fixes this PR.

@wfeller: I just copy and pasted the relevant code from your fork and I didn't grab your tests. If you'd like, open a new PR with your fix/tests and I'll close this one.

**Comment by calebporzio** [comment]
Thanks everyone for working on this.

Just to be uber clear: this will prevent parent's event listeners registered in the boot method from firing when the child registers it's own events?

If that is the case we are good. Just want to make sure this is in-line with the behavior people would expect when using this package, and we aren't going to confuse people by messing with their listeners.

I pulled it into master, but will hold off on tagging a version until I hear back from y'all.

**Comment by wfeller** [comment]
Hi @calebporzio,

It only prevents events registered in the parent's boot method from being fired twice on models that are registered as `$childTypes`.

Let's take the following example:

```php
class Vehicle extends Model
{
    use HasChildren;
    
    protected $childTypes = ['car' => Car::class];

    public static function boot ()
    {
        parent::boot();

        static::created($listener_1);
    }
}
```

```php
class Car extends Vehicle
{
    use HasParent;

    public static function boot ()
    {
        parent::boot();

        static::created($listener_2);
    }
}
```

```php
class Truck extends Vehicle
{
    use HasParent;
}
```

Previous behaviour:
- $listener_1 gets called once on Vehicle creation
- $listener_1 gets called **twice** on Car creation
- $listener_1 gets called once on Truck creation
- $listener_2 gets called once on Car creation

New (and expected) behaviour:
- $listener_1 gets called once on Vehicle creation
- $listener_1 gets called **once** on Car creation
- $listener_1 gets called once on Truck creation
- $listener_2 gets called once on Car creation

Hope it's all clear now :)

**Comment by calebporzio** [comment]
Great, thanks for clarifying - will tag a release.

**Pull request merged**
