### PR TITLE
Feature/allow mapping of children types

### PR DESCRIPTION
**Pull request by dallincoons**

### CODE REVIEW

**Comment by calebporzio** [comment]
Hey @dallincoons - what is the benefit of this feature (also mind explaining the feature in the description for others)?

If the only benefit is aliasing child types to more readable names, I would probably hold off on this. It widens the codebase without providing a ton of value IMO.

Maybe we hold off on this and see if anyone else has the need too?

Also, feel free to just PR the test cleanups you have - that would be helpful.

**Comment by dallincoons** [comment]
Right now I'm working off of my fork that implements this feature, because I have tables with existing type columns that aren't class names. I also don't particularly like storing class names in the database. It's a little too tied to the code. Also the assumption with storing class names is that you will only use the type column for this specific implementation of single table inheritance, but there can also be other uses for the type column in addition to that. 

Anyone who is including this package into an existing codebase with pre-existing type columns is probably going to need this.

**Comment by calebporzio** [comment]
Ah, ok - I could see that. I'll pull it in and add some Docs for it. Thanks

**Comment by calebporzio** [comment]
v0.4-alpha now has the feature. I changed the property name and added functionality for setting the column to the alias on creation.

**Comment by dallincoons** [comment]
Awesome, good to hear 👍

**Comment by dallincoons** [comment]
Speaking of doc updates, are you planning to update the readme to reflect the latest release version?

**Pull request merged**
